//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tetris_stacking_position_picker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tetris_stacking_position_picker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   現在の動画ファイルをクリアしてよいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_CLEAR {
            get {
                return ResourceManager.GetString("CONFIRM_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_CLEAR_CAPTION {
            get {
                return ResourceManager.GetString("CONFIRM_CLEAR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが大きいため不明です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_LOAD_1 {
            get {
                return ResourceManager.GetString("CONFIRM_LOAD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを全てロードしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_LOAD_2 {
            get {
                return ResourceManager.GetString("CONFIRM_LOAD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (ロードを行うと本処理の進捗がわかるようになります。) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_LOAD_3 {
            get {
                return ResourceManager.GetString("CONFIRM_LOAD_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロード確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_LOAD_CAPTION {
            get {
                return ResourceManager.GetString("CONFIRM_LOAD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画ファイルのオープンに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_FAIL_OPEN {
            get {
                return ResourceManager.GetString("ERROR_FAIL_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画ファイルを指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_INPUT_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_INPUT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出を停止できないため、アプリケーションを終了して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_KEEP_PICK {
            get {
                return ResourceManager.GetString("ERROR_KEEP_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在するファイルを指定して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_NOT_EXIST {
            get {
                return ResourceManager.GetString("ERROR_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロードがタイムアウトしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_TIMEOUT_LOADING_1 {
            get {
                return ResourceManager.GetString("ERROR_TIMEOUT_LOADING_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムアウト時間はアプリケーションの設定で変更できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_TIMEOUT_LOADING_2 {
            get {
                return ResourceManager.GetString("ERROR_TIMEOUT_LOADING_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例えば、 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_COLOR_1 {
            get {
                return ResourceManager.GetString("HINT_COLOR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ①動画をビデオのサイズでWindows Media Playerで再生して停める に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_COLOR_2 {
            get {
                return ResourceManager.GetString("HINT_COLOR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ②Windows Media PlayerをSnipping Toolでウィンドウキャプチャしてファイルに保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_COLOR_3 {
            get {
                return ResourceManager.GetString("HINT_COLOR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ③ファイルをペイントで開き、スポイトで色を抽出し、色の編集で色値を確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_COLOR_4 {
            get {
                return ResourceManager.GetString("HINT_COLOR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例えば、 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_POSITION_1 {
            get {
                return ResourceManager.GetString("HINT_POSITION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ①動画をビデオのサイズでWindows Media Playerで再生して停める に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_POSITION_2 {
            get {
                return ResourceManager.GetString("HINT_POSITION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ②Windows Media PlayerをSnipping Toolでウィンドウキャプチャしてファイルに保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_POSITION_3 {
            get {
                return ResourceManager.GetString("HINT_POSITION_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ③ファイルをペイントで開いて座標を特定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HINT_POSITION_4 {
            get {
                return ResourceManager.GetString("HINT_POSITION_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_COMPLETE_PICK {
            get {
                return ResourceManager.GetString("INFO_COMPLETE_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_CONTENT_1 {
            get {
                return ResourceManager.GetString("INFO_CONTENT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {2}{3}({4}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_CONTENT_2 {
            get {
                return ResourceManager.GetString("INFO_CONTENT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出を中止しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INFO_STOP_PICK {
            get {
                return ResourceManager.GetString("INFO_STOP_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [E]unknown mino に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_ERROR_UNKNOWN_MINO {
            get {
                return ResourceManager.GetString("LOG_ERROR_UNKNOWN_MINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   field({2}f) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_FIELD_FORMAT {
            get {
                return ResourceManager.GetString("LOG_FIELD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   game end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_GAME_END {
            get {
                return ResourceManager.GetString("LOG_GAME_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   game start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_GAME_START {
            get {
                return ResourceManager.GetString("LOG_GAME_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}({1}f): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_TIMESTAMP_FORMAT {
            get {
                return ResourceManager.GetString("LOG_TIMESTAMP_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NEXT_自作 {
            get {
                object obj = ResourceManager.GetObject("NEXT_自作", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   抽出中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STATUS_PICKING {
            get {
                return ResourceManager.GetString("STATUS_PICKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNIT_FPS {
            get {
                return ResourceManager.GetString("UNIT_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フレーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNIT_FRAME {
            get {
                return ResourceManager.GetString("UNIT_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap プレイ終了1_自作 {
            get {
                object obj = ResourceManager.GetObject("プレイ終了1_自作", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap プレイ終了2_自作 {
            get {
                object obj = ResourceManager.GetObject("プレイ終了2_自作", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap プレイ開始_自作 {
            get {
                object obj = ResourceManager.GetObject("プレイ開始_自作", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
